site_name: ESP32 SvelteKit

nav:
  - Home: index.md
  - "Toolings":
      - toolings.md
  - "Front End":
      - frontend.md
  - "Back End":
      - backend.md
  - "Documentation":
      - mkdocs.md

site_author: elims
site_description: >-
  A simple, secure and extensible framework for IoT projects on ESP32 platforms with responsive Sveltekit front-end built with TailwindCSS and DaisyUI.

# Repository
repo_name: theelims/ESP32-sveltekit
repo_url: https://github.com/theelims/ESP32-sveltekit

theme:
  name: material
  # logo: assets/logo.svg
  # favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: blue
      accent: blue

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    #  - toc.integrate
    - toc.follow
    - navigation.top
    #  - navigation.footer

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theelims/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

copyright: |
  Copyright &copy; 2023 by <a href="https://github.com/theelims"  target="_blank" rel="noopener">elims</a> -
  <a href="#__consent">Change cookie settings</a>
